---
secrets: /home/pi/HomeAssistant/config/secrets.yaml
logs:
  access_log: 
    filename: /export/appdaemon/logs/access.log
  error_log: 
    filename:/export/appdaemon/logs/error.log
  main_log: 
    filename: /export/appdaemon/logs/appdaemon.log
appdaemon:
  latitude: 43.603901
  longitude: -116.191852
  elevation: 858
  time_zone: America/Boise
  plugins:
    HASS:
      type: hass
      token: !secret hass_token
      ha_url: http://192.168.10.6:8123
    MQTT:
      type: mqtt
      client_host: 192.168.10.6
      namespace: default
      birth_topic: appdaemon
      will_topic: appdaemon
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
