
version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
 # appdaemon:
 #   container_name: appdaemon
 #   image: acockburn/appdaemon:latest
 #   environment:
 #     - HA_URL="http://192.168.10.10:8123"
 #     - TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI3NWE3YjVjYjkwMTk0MjMxODk4OTM4NjFmZGVlMGZkOCIsImlhdCI6MTY0MjM5MTQ1NywiZXhwIjoxOTU3NzUxNDU3fQ.CRFkrJu0YGdxHFWgkJnKnJnNPpDcPn8Obq9DkSWEz64"
 #     - DASH_URL=http://192.168.10.10:5050
 #   ports:
 #     - 5050:5050
 #   volumes:
 #     - /data/docker/HA/appdaemon/config:/conf
 #   depends_on:
 #     - homeassistant
  esphome:
    #image: esphome/esphome:beta
    #image: esphome/esphome:dev
    image: esphome/esphome:latest
    devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/bus/usb:/dev/bus/usb"
    # - "/dev/ttyS3:/dev/ttyUSB0"
    privileged: true
    container_name: esphome
    volumes:
      - ./config/esphome/config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # network_mode: host
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6152:6052
      - 6123:6123
    restart: unless-stopped

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=gtresgtrshtyrs
      - ZWAVEJS_EXTERNAL_CONFIG=/home/pi/HomeAssistant/config/zwavejs/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Boise
    networks:
      - zwave
    devices: 
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
       - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - zwave-config:/home/pi/HomeAssistant/config/zwavejs/
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      # - 53:53/tcp
      # - 53:53/udp
      # - 784:784/udp
      # - 853:853/tcp
      # - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./config/adguardhome/workdir:/opt/adguardhome/work
      - ./config/adguardhome/config/confdir:/opt/adguardhome/conf
    restart: unless-stopped

networks:
  zwave:
volumes:
  zwave-config:
    #name: zwave-config
