- id: '1238451014602'
  alias: sensor_values_to_file
  trigger:
  - platform: time_pattern
    seconds: /1
  action:
  - service: notify.filenotify
    data_template:
      message: '{{states.input_select.room_for_training.last_changed}}, {{states.input_select.room_for_training.state
        }},  {{states.sensor.steven_beacon_rssi_bedroom_2.last_changed }},  {{states.sensor.steven_beacon_rssi_bedroom_2.state
        }},  {{states.sensor.steven_beacon_rssi_kitchen_2.last_changed }}, {{states.sensor.steven_beacon_rssi_kitchen_2.state
        }},  {{states.sensor.steven_beacon_rssi_living_room_2.last_changed }},  {{states.sensor.steven_beacon_rssi_living_room_2.state
        }},  {{states.sensor.steven_beacon_rssi_office_2.last_changed }}, {{states.sensor.steven_beacon_rssi_office_2.state
        }}'
