esphome:
  name: brewstation

esp8266:
  board: d1_mini

# Enable logging
logger:

globals:
  - id: heater_percent_pwm
    type: int
    #restore_value: yes
    initial_value: '0'  # 0..100

# Enable Home Assistant API
api:
  services:
    - service: set_heater_percent_pwm
      variables:
        percentage: int
      then:
        - lambda: |-
            id(heater_percent_pwm) = percentage;
            id(heater_sensor).publish_state(percentage);

ota:
  password: "03bc1ef147f7d6f69f1f3c1d716188c6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Brestation Fallback Hotspot"
    password: "PmQKhi6uVOPf"

captive_portal:

dallas:
  - pin: D1
    update_interval: 1s
  
sensor:
  - platform: dallas
    index: 0
    name: "Water Temperature"
  - platform: template
    name: "Heater Sensor (PWM level)"
    id: heater_sensor
    lambda: 'return id(heater_percent_pwm);'
    update_interval: 1s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:pulse"
    on_value:
      then:
        - lambda: |-
            id(heater_percent_pwm_output).set_level(x/100);
output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 1000 Hz
    id: heater_percent_pwm_output
    inverted: False
    min_power: 0.00
    max_power: 1.00
   
