appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
      ha_url: "http://192.168.10.10:8123"
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI3NWE3YjVjYjkwMTk0MjMxODk4OTM4NjFmZGVlMGZkOCIsImlhdCI6MTY0MjM5MTQ1NywiZXhwIjoxOTU3NzUxNDU3fQ.CRFkrJu0YGdxHFWgkJnKnJnNPpDcPn8Obq9DkSWEz64"
http:
  url: http://192.168.10.10:5050
admin:
api:
hadashboard:
